# Generated by Django 5.2.17 on 2026-08-22 08:58

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sincronizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("fecha_ejecucion", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("iniciado_at", models.DateTimeField(auto_now_add=True)),
                ("finalizado_at", models.DateTimeField(blank=True, null=True)),
                ("usuario_origen", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "sincronizaciones",
                "indexes": [
                    models.Index(
                        fields=["estado", "iniciado_at"], name="idx_sync_estado_inicio"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "estado__in",
                                [
                                    "pending",
                                    "running",
                                    "completed",
                                    "failed",
                                    "rejected",
                                ],
                            )
                        ),
                        name="sync_estado_valido",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LogError",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("servicio_responsable", models.CharField(max_length=100)),
                (
                    "nivel_error",
                    models.CharField(
                        choices=[
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("codigo_error", models.CharField(max_length=50)),
                ("mensaje", models.TextField()),
                ("stack_trace", models.TextField(blank=True, null=True)),
                (
                    "creado_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "sincronizacion",
                    models.ForeignKey(
                        db_column="correlation_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_errores",
                        to="sync.sincronizacion",
                        to_field="correlation_id",
                    ),
                ),
            ],
            options={
                "db_table": "logs_errores",
                "indexes": [
                    models.Index(
                        fields=["nivel_error", "creado_at"], name="idx_log_nivel_fecha"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("nivel_error__in", ["WARNING", "ERROR", "CRITICAL"])
                        ),
                        name="log_nivel_valido",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArchivoProcesado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_archivo", models.CharField(max_length=255)),
                (
                    "tipo_archivo",
                    models.CharField(
                        choices=[
                            ("ventas", "Ventas"),
                            ("inventario", "Inventario"),
                            ("clientes", "Clientes"),
                        ],
                        max_length=20,
                    ),
                ),
                ("checksum", models.CharField(max_length=64, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("registros_totales", models.IntegerField(db_default=0, default=0)),
                ("datos_payload", models.JSONField(blank=True, null=True)),
                (
                    "sincronizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos_procesados",
                        to="sync.sincronizacion",
                    ),
                ),
            ],
            options={
                "db_table": "archivos_procesados",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tipo_archivo__in", ["ventas", "inventario", "clientes"])
                        ),
                        name="archivo_tipo_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("estado__in", ["accepted", "rejected"])),
                        name="archivo_estado_valido",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccionRemediacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("accion_ejecutada", models.CharField(max_length=100)),
                ("ejecutado_por", models.CharField(max_length=100)),
                (
                    "resultado",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "sincronizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones_remediacion",
                        to="sync.sincronizacion",
                    ),
                ),
            ],
            options={
                "db_table": "acciones_remediacion",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("resultado__in", ["success", "failed"])),
                        name="remediacion_resultado_valido",
                    )
                ],
            },
        ),
    ]
